apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: s8f9dqlb2-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/s8f9dqlb2-java-quarkus-gitops